name: Update README.md with Random Library

on:
  schedule:
    - cron: '0 0 * * *' # Exécuter tous les jours à minuit UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Update README.md with a random library
      run: |
        # Define a list of libraries
        libraries=(
          "jQuery - Library that simplifies HTML document traversal and manipulation, event handling, and animation."
          "React - Library for building user interfaces."
          "Lodash - Utility library that provides modular methods for common programming tasks."
          "Moment.js - Library for parsing, validating, manipulating, and formatting dates."
          "Axios - Promise-based HTTP client for making requests."
          "Three.js - Library for creating 3D graphics on the web."
          "D3.js - Library for producing dynamic, interactive data visualizations."
          "Anime.js - JavaScript animation library with a simple API."
          "Chart.js - Simple yet flexible JavaScript charting library."
          "GrapesJS - Open-source web builder framework."
          "GreenSock (GSAP) - Library for high-performance animations."
          "Redux - Library for managing and centralizing application state."
          "Vuex - State management pattern + library for Vue.js applications."
          "Express - Web application framework for Node.js."
          "Socket.io - Library for real-time web applications."
          "PixiJS - 2D rendering library for the web."
          "HandBrake.js - JavaScript library for video encoding."
          "Alpine.js - Minimal framework for composing JavaScript behavior in your HTML."
          "Popper.js - Library for managing poppers (tooltips, popovers)."
          "Jest - JavaScript testing framework."
          "Prettier - Code formatter for consistent style."
          "TypeScript - Superset of JavaScript with static types."
          "Webpack - Module bundler for JavaScript applications."
          "Parcel - Blazing fast, zero configuration web application bundler."
          "Gulp - Toolkit for automating time-consuming tasks in your development workflow."
        )
        
        # Choose a random library from the list
        random_library=${libraries[$((RANDOM % ${#libraries[@]}))]}
        
        # Generate the README.md content with the random library
        cat <<EOF > README.md
<meta name="description" content="GitHub profile in blue color">
<meta name="keywords" content="Full Stack Developer, GitHub Stats, GitHub Profile, JavaScript, TypeScript, React, Nodejs, HTML5, CSS3, PHP, MySQL, MongoDB"/>

<div>
   <img width=100% src="https://capsule-render.vercel.app/api?type=waving&color=007acc&height=120&section=header">
</div>

<img src="https://readme-typing-svg.herokuapp.com/?color=1BF7B3&size=35&center=true&weight=700&size=40&pause=1500&&vCenter=true&width=1000&lines=Hi,+I'm+Manu;I'm+a+Full+Stack+Js+Developer;Be+Welcome!+😁">

<br/>  
<br/>  

<table align="center" style="border-radius: 15px;">
  <tr>
    <td valign="top" width="33%" style="border: 2px solid black; padding: 10px; background-color: #f9f9f9;">
      <br>
      <img src="https://readme-typing-svg.herokuapp.com?font=Fira+Code&weight=700&size=40&duration=2000&pause=99000&center=true&vCenter=truerandom=false&reapeat=false&width=435&height=100&lines=Frontend">
      <p align="center">
        <a href="https://skillicons.dev">
          <img src="https://skillicons.dev/icons?i=html,sass,js,vue,react,ts" />
        </a>
      </p>
    </td>
    <td valign="top" width="33%" style="border: 2px solid black; padding: 10px; background-color: #e9e9e9;">
      <br>
      <img src="https://readme-typing-svg.herokuapp.com?font=Fira+Code&weight=700&size=40&duration=2000&pause=99000&center=true&vCenter=truerandom=false&reapeat=false&width=435&height=100&lines=Backend">
      <p align="center">
        <a href="https://skillicons.dev">
          <img src="https://skillicons.dev/icons?i=php,docker,mysql" />
        </a>
      </p>
    </td>
    <td valign="top" width="33%" style="border: 2px solid black; padding: 10px; background-color: #d9d9d9;">
      <br>
      <img src="https://readme-typing-svg.herokuapp.com?font=Fira+Code&weight=700&size=40&duration=2000&pause=99000&center=true&vCenter=truerandom=false&reapeat=false&width=435&height=100&lines=Other">
      <p align="center">
        <a href="https://skillicons.dev">
          <img src="https://skillicons.dev/icons?i=git,py,linux" />
        </a>
      </p>
    </td>
  </tr>
  <tr>
    <td colspan="3" valign="top" style="border: 2px solid black; padding: 10px; background-color: #c9c9c9;">
      <br>
      <div align="center">
        <img src="https://readme-typing-svg.herokuapp.com?font=Fira+Code&weight=700&size=30&duration=1000&pause=99000&center=true&vCenter=truerandom=false&reapeat=false&width=435&height=100&lines=I+learn">
      </div>
      <p align="center">
        <a href="https://skillicons.dev">
          <img src="https://skillicons.dev/icons?i=svelte,angular,nodejs,mongodb" />
        </a>
      </p>
    </td>
  </tr>
</table>

<br/>  

###

<div align="center">
  <img height="190rem" alt="GitHub Stats" src="https://github-readme-stats.vercel.app/api?username=manu-cj&show_icons=true&title_color=007acc&icon_color=007acc&text_color=007acc&bg_color=00000000&border_radius=15&border_color=00000000&count_private=true&hide=contribs&hide_rank=true"/>
  <img height="190rem" alt="Most Used Languages" src="https://github-readme-stats.vercel.app/api/top-langs/?username=manu-cj&langs_count=6&layout=compact&title_color=007acc&icon_color=007acc&text_color=007acc&bg_color=00000000&border_radius=15&border_color=00000000&hide=css,html,hack,Dockerfile,scss"/>
</div>

<div align="center">
  <img src="https://github-readme-streak-stats.herokuapp.com/?user=manu-cj&theme=react&langs_count=6&layout=compact&title_color=007acc&icon_color=007acc&text_color=007acc&bg_color=00000000&border_radius=15&border_color=00000000&hide=jupyter%20notebook" height="200px" />
</div>
<br>
<div align="center">
  <a href="https://www.linkedin.com/in/manu-cj" target="_blank">
    <img height="30" width="120" title="linkedin.com/in/manu-cj/" src="./linkedin.png">
  </a>
</div>

<a href="#">
  <img width=100% src="https://capsule-render.vercel.app/api?type=waving&color=007acc&height=120&section=footer"/>
</a> 

<h2 align="center">My activity</h2>

<div align="center">
  <img src="https://github.com/manu-cj/manu-cj/blob/output/github-contribution-grid-snake-dark.svg">
</div>

<h2 align="center">Random JavaScript Library</h2>

<p align="center">Here is a random JavaScript library that you might find useful:</p>

<p align="center"><b>${random_library}</b></p>

EOF
